---
name: Pipeline

on:
  push:
    branches:
      - main

jobs:
  conform:
    runs-on: ubuntu-latest
    name: Conform

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        run: ./gradlew test

  spectral:
    name: Spectral Linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: jaxxstorm/action-install-gh-release@v1.12.0
        with:
          repo: stoplightio/spectral
          extension-matching: disable
          rename-to: spectral
          chmod: 0755

      - run: |
          spectral lint 'docs/**/*.yaml' --fail-severity info
          spectral lint 'docs/**/*.yml' --fail-severity info

  yamllint:
    name: YAMLLint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: yamllint docs