---
name: Pipeline

on:
  push:
    branches:
      - main

jobs:
  conform:
    runs-on: ubuntu-latest
    name: Conform

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        run: ./gradlew test